### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [sierscse/prj-rev-bwfs-dasmoto#6]
Satisfactory 👍 

Great job reproducing the web page according to the design mock. You've written some very efficient CSS as well, good job!

Improve your HTML by using `div` tags to _divide_ your page into sections. You have three item sections, so you can have a container `div` around each section with a class of `item` or `product`.

**Comment by sierscse** [comment]
Thank you! This is very helpful. I've made the suggested changes locally. After I learn more about github I hope to push the changes here to master.
